language: ruby
rvm:
  - 2.1.2
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
script:
  - RAILS_ENV=test bundle exec rake spec
notifications:
  email: false
