
emop:
  adapter: mysql2
  database: emop
  username: root
  password: 
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  adapter: mysql2

test:
  adapter: mysql2

production:
  adapter: mysql2