# 
# Define eMOP configuration settings based on environment
#
# All properties starting with juxta_ws_ define connection
# parameters to the Juxta Web Service
#
# emop_path_prefix is used in development and testing to add a
# path prefix to the paths found in the eMOP database.
#
#
development:
  juxta_ws_url: http://127.0.0.1:8182/juxta
  juxta_ws_user: juxta
  juxta_ws_pass: 
  emop_path_prefix:
    
test:
  juxta_ws_url: http://127.0.0.1:8182/juxta
  juxta_ws_user: juxta
  juxta_ws_pass: 
  emop_path_prefix:

production:
  juxta_ws_url: http://127.0.0.1:8182/juxta
  juxta_ws_user: juxta
  juxta_ws_pass: 
  emop_path_prefix: